core:
- changed-files:
  - any-glob-to-any-file: 'core/**'

ci:
- changed-files:
  - any-glob-to-any-file: '.github/**'

kotlin:
- changed-files:
  - any-glob-to-any-file: ['languages/kotlin/**', 'examples/kotlin/**']
