// This file is generated by custom shader compiler. DO NOT EDIT.
#ifndef GRAPHICS_VULKAN_SHADERS_SHADER_LAYOUT_H
#define GRAPHICS_VULKAN_SHADERS_SHADER_LAYOUT_H

#include <cstdint>

namespace karin::gen {

namespace vertex_vert_main{

inline constexpr uint32_t matrices_set = 0;
inline constexpr uint32_t matrices_binding = 0;

inline constexpr uint32_t max_set = 0;

}
namespace geometry_frag_main{

inline constexpr uint32_t tex_tex_set = 1;
inline constexpr uint32_t tex_tex_binding = 0;
inline constexpr uint32_t tex_samp_set = 1;
inline constexpr uint32_t tex_samp_binding = 1;
inline constexpr uint32_t matrices_set = 0;
inline constexpr uint32_t matrices_binding = 0;

inline constexpr uint32_t max_set = 1;

}
namespace text_frag_main{

inline constexpr uint32_t tex_tex_set = 1;
inline constexpr uint32_t tex_tex_binding = 0;
inline constexpr uint32_t tex_samp_set = 1;
inline constexpr uint32_t tex_samp_binding = 1;
inline constexpr uint32_t glyphAtlas_tex_set = 2;
inline constexpr uint32_t glyphAtlas_tex_binding = 0;
inline constexpr uint32_t glyphAtlas_samp_set = 2;
inline constexpr uint32_t glyphAtlas_samp_binding = 1;
inline constexpr uint32_t matrices_set = 0;
inline constexpr uint32_t matrices_binding = 0;

inline constexpr uint32_t max_set = 2;

}

} // karin::gen

#endif // GRAPHICS_VULKAN_SHADERS_SHADER_LAYOUT_H
