name: setup-vulkan-ubuntu
description: Setup Vulkan SDK in ubuntu

runs:
  using: "composite"
  steps:
    - name: Setup Vulkan SDK apt repository
      run: |
        wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-noble.list http://packages.lunarg.com/vulkan/lunarg-vulkan-noble.list
        sudo apt update
      shell: bash