/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_kavos113_karin_JniRectangleNode */

#ifndef _Included_com_github_kavos113_karin_JniRectangleNode
#define _Included_com_github_kavos113_karin_JniRectangleNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_kavos113_karin_JniRectangleNode
 * Method:    create
 * Signature: (FFFFFF)J
 */
JNIEXPORT jlong JNICALL Java_com_github_kavos113_karin_JniRectangleNode_create
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
