/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_kavos113_karin_engine_jni_JniViewNode */

#ifndef _Included_com_github_kavos113_karin_engine_jni_JniViewNode
#define _Included_com_github_kavos113_karin_engine_jni_JniViewNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_kavos113_karin_engine_jni_JniViewNode
 * Method:    setClickListener
 * Signature: (JLcom/github/kavos113/karin/ViewNode;)V
 */
JNIEXPORT void JNICALL Java_com_github_kavos113_karin_engine_jni_JniViewNode_setClickListener
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
