/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_kavos113_karin_engine_jni_JniContainerNode */

#ifndef _Included_com_github_kavos113_karin_engine_jni_JniContainerNode
#define _Included_com_github_kavos113_karin_engine_jni_JniContainerNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_kavos113_karin_engine_jni_JniContainerNode
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_kavos113_karin_engine_jni_JniContainerNode_create__
  (JNIEnv *, jclass);

/*
 * Class:     com_github_kavos113_karin_engine_jni_JniContainerNode
 * Method:    create
 * Signature: (FF)J
 */
JNIEXPORT jlong JNICALL Java_com_github_kavos113_karin_engine_jni_JniContainerNode_create__FF
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     com_github_kavos113_karin_engine_jni_JniContainerNode
 * Method:    addChild
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_github_kavos113_karin_engine_jni_JniContainerNode_addChild
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_github_kavos113_karin_engine_jni_JniContainerNode
 * Method:    setLayoutDirection
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_github_kavos113_karin_engine_jni_JniContainerNode_setLayoutDirection
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_kavos113_karin_engine_jni_JniContainerNode
 * Method:    setGap
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_github_kavos113_karin_engine_jni_JniContainerNode_setGap
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_github_kavos113_karin_engine_jni_JniContainerNode
 * Method:    setWrapMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_github_kavos113_karin_engine_jni_JniContainerNode_setWrapMode
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
