/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_kavos113_karin_JniApplication */

#ifndef _Included_com_github_kavos113_karin_JniApplication
#define _Included_com_github_kavos113_karin_JniApplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_kavos113_karin_JniApplication
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_kavos113_karin_JniApplication_create
  (JNIEnv *, jclass);

/*
 * Class:     com_github_kavos113_karin_JniApplication
 * Method:    createWindow
 * Signature: (JLjava/lang/String;IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_github_kavos113_karin_JniApplication_createWindow
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint, jint);

/*
 * Class:     com_github_kavos113_karin_JniApplication
 * Method:    run
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_kavos113_karin_JniApplication_run
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_kavos113_karin_JniApplication
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_kavos113_karin_JniApplication_destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
