/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_kavos113_karin_JniWindow */

#ifndef _Included_com_github_kavos113_karin_JniWindow
#define _Included_com_github_kavos113_karin_JniWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_kavos113_karin_JniWindow
 * Method:    setRootView
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_github_kavos113_karin_JniWindow_setRootView
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_github_kavos113_karin_JniWindow
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_kavos113_karin_JniWindow_destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
