/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_kavos113_karin_engine_jni_JniTextNode */

#ifndef _Included_com_github_kavos113_karin_engine_jni_JniTextNode
#define _Included_com_github_kavos113_karin_engine_jni_JniTextNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_kavos113_karin_engine_jni_JniTextNode
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;IIIFLjava/lang/String;ZZIIFFIIIIIFFFF)J
 */
JNIEXPORT jlong JNICALL Java_com_github_kavos113_karin_engine_jni_JniTextNode_create
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jint, jfloat, jstring, jboolean, jboolean, jint, jint, jfloat, jfloat, jint, jint, jint, jint, jint, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
