name: "Core Build - Windows"

on:
  workflow_call:
    inputs:
      cmake-build-type:
        required: true
        type: string
      cmake-preset:
        required: true
        type: string
      build-dir:
        required: true
        type: string

jobs:
  core-build:
    runs-on: windows-latest

    permissions:
      contents: read

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install windows dependencies
        run: |
          choco install ninja -y

      - name: Vcpkg Cache
        id: cache-vcpkg
        uses: actions/cache@v4
        with:
          path: |
            .\vcpkg
            .\${{ inputs.build-dir }}\${{ inputs.cmake-preset }}\vcpkg_installed
          key: ${{ inputs.cmake-preset }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ inputs.cmake-preset }}-vcpkg-

      - name: Install vcpkg
        run: |
          if (-not (Test-Path -Path .\vcpkg)) {
            git clone https://github.com/microsoft/vcpkg.git
          }
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Configure CMake
        run: |
          New-Item -Path .\${{ inputs.build-dir }} -ItemType Directory -Force
          Push-Location -Path .\${{ inputs.build-dir }}
          
          cmake -G Ninja `
            -DCMAKE_BUILD_TYPE=${{ inputs.cmake-build-type }} `
            -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake" `
            -DCMAKE_C_COMPILER=clang `
            -DCMAKE_CXX_COMPILER=clang++ `
            --preset ${{ inputs.cmake-preset }} ..

      - name: Build
        run: |
          Push-Location -Path .\${{ inputs.build-dir }}
          cmake --build ${{ inputs.cmake-preset }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: core-${{ inputs.cmake-preset }}-build
          path: ${{ inputs.build-dir }}
          overwrite: 'true'