name: setup-vulkan-windows
description: Setup Vulkan SDK in windows

inputs:
  vulkan-version:
    description: version of Vulkan SDK
    required: true

runs:
  using: "composite"
  steps:
    - name: Vulkan SDK Installer Cache
      id: cache-vulkan-sdk
      uses: actions/cache@v4
      with:
        path: VulkanSDK-Installer.exe
        key: vulkan-sdk-${{ inputs.vulkan-version }}-${{ runner.os }}-installer
        restore-keys:
          - vulkan-sdk-${{ inputs.vulkan-version }}-${{ runner.os }}-installer

    - name: Download Vulkan SDK from Cache
      if: steps.cache-vulkan-sdk.outputs.cache-hit == 'true'
      run: |
        INSTALLER_URL="https://sdk.lunarg.com/sdk/download/${{ inputs.vulkan-version }}/windows/vulkansdk-windows-X64-${{ inputs.vulkan-version }}.exe"
        INSTALLER_PATH="./VulkanSDK-Installer.exe"
        INSTALL_DIR="C:/VulkanSDK/${{ inputs.vulkan-version }}"
        
        echo "Downloading Vulkan SDK version ${{ inputs.vulkan-version }}..."
        curl -L -o "$INSTALLER_PATH" "$INSTALLER_URL"
      shell: bash

    - name: Install Vulkan SDK
      run:
        INSTALLER_PATH="./VulkanSDK-Installer.exe"
        INSTALL_DIR="C:/VulkanSDK/${{ inputs.vulkan-version }}"
        
        echo "Installing Vulkan SDK to $INSTALL_DIR..."
        "$INSTALLER_PATH" --root "$INSTALL_DIR" --accept-licenses --default-answer --confirm-command install
        
        echo "Vulkan SDK setup complete."
      shell: bash

    - name: Setup Vulkan Environment
      run: |
        echo "Setting up Vulkan environment variables..."
        echo "VULKAN_SDK=C:/VulkanSDK/${{ inputs.vulkan-version }}" >> $GITHUB_ENV
        echo "VK_LAYER_PATH=C:/VulkanSDK/${{ inputs.vulkan-version }}/Bin" >> $GITHUB_ENV
        echo "$VULKAN_SDK/Bin" >> $GITHUB_PATH
        echo "$VULKAN_SDK/Lib" >> $GITHUB_PATH  
        echo "$VULKAN_SDK/Include" >> $GITHUB_PATH
      shell: bash