#include "generator.h"

#include <cstdint>

#include <fstream>
#include <format>
#include <utility>

#include <slang.h>
#include <slang-com-ptr.h>

#include "util.h"

CodeGenerator::CodeGenerator(std::string  outFile)
    : m_outFile(std::move(outFile))
{
}

CodeGenerator::~CodeGenerator() = default;

void CodeGenerator::generate(const std::vector<ShaderModule>& modules, const std::string& includeGuard) const
{
    // mark binary to force LF
    std::ofstream ofs(m_outFile, std::ios::binary);

    writeHeader(ofs, includeGuard);

    for (const auto& mod : modules)
    {
        writeCode(ofs, mod);
    }

    writeFooter(ofs, includeGuard);

    ofs.close();
}

void CodeGenerator::writeHeader(std::ostream& os, const std::string& includeGuard)
{
    os << "// This file is generated by custom shader compiler. DO NOT EDIT.\n"
       << "#ifndef " << includeGuard << "\n"
       << "#define " << includeGuard << "\n"
       << "\n"
       << "#include <cstddef>\n"
       << "\n"
       << "#include <array>\n"
       << "\n"
       << "namespace karin::gen {\n\n"
       << "using b = std::byte;\n"
       << "\n";
}

void CodeGenerator::writeFooter(std::ostream& os, const std::string& includeGuard)
{
    os << "\n"
       << "} // karin::gen\n"
       << "\n"
       << "#endif // " << includeGuard << "\n";
}

void CodeGenerator::writeCode(std::ostream& os, const ShaderModule& module)
{
    auto buffer = module.spirvCode();

    size_t size = buffer->getBufferSize();
    std::string varName = module.identifier();

    const char *buf = static_cast<const char*>(buffer->getBufferPointer());

    os << "inline constexpr std::array<std::byte, " << size << "> " << varName << " = {\n";

    for (int i = 0; i < size; i += CODE_WIDTH)
    {
        os << "   ";

        for (int curr = i; i < std::min(curr + CODE_WIDTH, static_cast<int>(size)); i++)
        {
            const char byte = buf[curr];
            os << std::format(" b{{0x{:02x}}},", byte);
        }

        os << "\n";
    }

    os << "};\n\n";
}

LayoutGenerator::LayoutGenerator(const std::string& outFile)
    : m_outFile(outFile)
{
}

LayoutGenerator::~LayoutGenerator() = default;

void LayoutGenerator::generate(const std::vector<ShaderModule>& modules, const std::string& includeGuard) const
{
    // mark binary to force LF
    std::ofstream ofs(m_outFile, std::ios::binary);

    writeHeader(ofs, includeGuard);

    for (const auto& mod : modules)
    {
        writeLayout(ofs, mod);
    }

    writeFooter(ofs, includeGuard);

    ofs.close();
}

void LayoutGenerator::writeHeader(std::ostream& os, const std::string& includeGuard)
{
    os << "// This file is generated by custom shader compiler. DO NOT EDIT.\n"
       << "#ifndef " << includeGuard << "\n"
       << "#define " << includeGuard << "\n"
       << "\n"
       << "#include <cstdint>\n"
       << "\n"
       << "namespace karin::gen {\n"
       << "\n";
}

void LayoutGenerator::writeFooter(std::ostream& os, const std::string& includeGuard)
{
    os << "\n"
       << "} // karin::gen\n"
       << "\n"
       << "#endif // " << includeGuard << "\n";
}

void LayoutGenerator::writeLayout(std::ostream& os, const ShaderModule& module)
{
    os << "namespace " << module.identifier() << "{\n\n";

    Slang::ComPtr<slang::IBlob> diagnosticBlob;
    slang::ProgramLayout *programLayout = module.program()->getLayout(0, diagnosticBlob.writeRef()); // target = 0
    diagnose(diagnosticBlob);
    if (!programLayout)
    {
        throw std::runtime_error("failed to get program layout");
    }

    uint32_t paramsCount = programLayout->getParameterCount();

    for (uint32_t i = 0; i < paramsCount; i++)
    {
        slang::VariableLayoutReflection *varLayout = programLayout->getParameterByIndex(i);
        slang::TypeLayoutReflection *typeLayout = varLayout->getTypeLayout();

        switch (typeLayout->getKind())
        {
            using enum slang::TypeReflection::Kind;

        case Struct:
            {
                slang::VariableReflection *structVar = varLayout->getVariable();

                uint32_t paramCount = typeLayout->getFieldCount();

                for (uint32_t j = 0; j < paramCount; j++)
                {
                    slang::VariableLayoutReflection *childVarLayout = typeLayout->getFieldByIndex(j);
                    slang::VariableReflection *var = childVarLayout->getVariable();
                    if (var == nullptr)
                    {
                        continue;
                    }

                    uint32_t set = childVarLayout->getBindingSpace();
                    uint32_t binding = childVarLayout->getBindingIndex();

                    os << "inline constexpr uint32_t " << structVar->getName() << "_" << var->getName() << "_set = " << set << ";\n"
                       << "inline constexpr uint32_t " << structVar->getName() << "_" << var->getName() << "_binding = " << binding << ";\n";
                }

                break;
            }

        case ParameterBlock:
            {
                uint32_t categoryCount = varLayout->getCategoryCount();
                assert(categoryCount > 0);

                slang::ParameterCategory category = varLayout->getCategoryByIndex(0);
                size_t set = varLayout->getOffset(category);

                slang::VariableReflection *blockVar = varLayout->getVariable();

                slang::VariableLayoutReflection *insideBlock = typeLayout->getElementVarLayout();
                slang::TypeLayoutReflection *insideType = insideBlock->getTypeLayout();

                if (insideType->getKind() == Struct)
                {
                    uint32_t paramCount = insideType->getFieldCount();

                    for (uint32_t j = 0; j < paramCount; j++)
                    {
                        slang::VariableLayoutReflection *layout = insideType->getFieldByIndex(j);
                        slang::VariableReflection *var = layout->getVariable();
                        if (var == nullptr)
                        {
                            continue;
                        }

                        uint32_t binding = layout->getBindingIndex();

                        os << "inline constexpr uint32_t " << blockVar->getName() << "_" << var->getName() << "_set = " << set << ";\n"
                           << "inline constexpr uint32_t " << blockVar->getName() << "_" << var->getName() << "_binding = " << binding << ";\n";
                    }
                }
                else
                {
                    slang::VariableReflection *var = insideBlock->getVariable();
                    if (var == nullptr)
                    {
                        continue;
                    }

                    uint32_t binding = insideBlock->getBindingIndex();

                    os << "inline constexpr uint32_t " << var->getName() << "_set = " << set << ";\n"
                       << "inline constexpr uint32_t " << var->getName() << "_binding = " << binding << ";\n";
                }

                break;
            }

        default:
            {
                slang::VariableReflection *var = varLayout->getVariable();
                if (var == nullptr)
                {
                    continue;
                }

                uint32_t set = varLayout->getBindingSpace();
                uint32_t binding = varLayout->getBindingIndex();

                os << "inline constexpr uint32_t " << var->getName() << "_set = " << set << ";\n"
                   << "inline constexpr uint32_t " << var->getName() << "_binding = " << binding << ";\n";

                break;
            }
        }

        // printVariable(varLayout);
    }

    os << "\n}\n";
}
