name: ci-windows-vulkan.yml
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  CMAKE_BUILD_TYPE: Release
  CMAKE_EXPORT_COMPILE_COMMANDS: true
  BUILD_DIR: build
  CMAKE_PRESET: windows-vulkan-debug-headless
  VULKAN_SDK_VERSION: 1.4.321.1

jobs:
  core-build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          choco install ninja -y

      - name: Setup Vulkan SDK
        uses: ./.github/actions/setup-vulkan-windows
        with:
          vulkan-version: ${{ env.VULKAN_SDK_VERSION }}

      - name: Vcpkg Cache
        id: cache-vcpkg
        uses: actions/cache@v4
        with:
          path: |
            .\vcpkg
            .\${{ env.BUILD_DIR }}\${{ env.CMAKE_PRESET }}\vcpkg_installed
          key: ${{ env.CMAKE_PRESET }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ env.CMAKE_PRESET }}-vcpkg-

      - name: Install vcpkg
        run: |
          if (-not (Test-Path -Path .\vcpkg)) {
            git clone https://github.com/microsoft/vcpkg.git
          }
          .\vcpkg\bootstrap-vcpkg.bat
        shell: pwsh

      - name: Configure CMake
        run: |
          New-Item -Path .\${{ env.BUILD_DIR }} -ItemType Directory -Force
          Push-Location -Path .\${{ env.BUILD_DIR }}
          
          cmake -G Ninja `
            -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} `
            -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake" `
            -DCMAKE_C_COMPILER=clang `
            -DCMAKE_CXX_COMPILER=clang++ `
            --preset ${{ env.CMAKE_PRESET }} ..

      - name: Build
        run: |
          Push-Location -Path .\${{ env.BUILD_DIR }}
          cmake --build ${{ env.CMAKE_PRESET }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: core-${{ env.CMAKE_PRESET }}-build
          path: ${{ env.BUILD_DIR }}
          overwrite: 'true'

  core-test:
    runs-on: windows-latest
    needs: [core-build]

    permissions:
      contents: read

    steps:
      - name: Download workflows
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            .github

      - name: Download build artifacts
        uses: actions/download-artifact@v8.0.1
        with:
          name: core-${{ env.CMAKE_PRESET }}-build
          path: .\${{ env.BUILD_DIR }}

      - parallel:
        - name: Setup Vulkan SDK
          uses: ./.github/actions/setup-vulkan-windows
          with:
            vulkan-version: ${{ env.VULKAN_SDK_VERSION }}

        - name: Setup SwiftShader
          uses: ./.github/actions/setup-swiftshader
          with:
            build-os: windows-latest

      - name: add swiftshader to registry
        run: |
          $JsonPath = '${{ github.workspace }}\swiftshader\build\Windows\vk_swiftshader_icd.json'
          Write-Host "Adding SwiftShader ICD to registry with JSON path: $JsonPath"

          if (-not (Test-Path "HKLM:\SOFTWARE\Khronos\Vulkan\Drivers")) {
              New-Item -Path "HKLM:\SOFTWARE\Khronos\Vulkan\Drivers" -Force
          }

          New-ItemProperty -Path "HKLM:\SOFTWARE\Khronos\Vulkan\Drivers" -Name $JsonPath -Value 0 -PropertyType DWord -Force
          Write-Host "SwiftShader ICD added to registry successfully."
        shell: pwsh

      - name: Run tests
        env:
          VK_ICD_FILENAMES: '${{ github.workspace }}\swiftshader\build\Windows\vk_swiftshader_icd.json'
          UPDATE_TEST_IMAGES: 0
          TEST_PROFILE: windows-vulkan
        run: |
          Push-Location -Path .\${{ env.BUILD_DIR }}\${{ env.CMAKE_PRESET }}\core\test
          ctest --output-on-failure

  kotlin-test:
    runs-on: windows-latest
    needs: [core-build]

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Download build artifacts
        uses: actions/download-artifact@v8.0.1
        with:
          name: core-${{ env.CMAKE_PRESET }}-build
          path: ${{ env.BUILD_DIR }}

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Build Kotlin Bindings
        id: build-bindings
        working-directory: .\languages\kotlin
        background: true
        run: |
          .\gradlew build

      - name: Build Kotlin Examples
        working-directory: .\examples\kotlin
        background: true
        run: |
          .\gradlew build

      - name: Wait build binding
        wait: [build-bindings]

      - name: Run Kotlin Tests
        working-directory: .\languages\kotlin
        run: |
          .\gradlew test

      - name: Rate coverage
        working-directory: .\languages\kotlin
        run: |
          .\gradlew koverPrintCoverage